name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: programa
          path: ./dist


      - name: Debug files
        run: |
          echo "Arquivos na raiz:"
          ls -la
          echo "Arquivos em dist:"
          ls -la dist

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: mairacna
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mairacna/go_ci:${{ github.ref_name }}
